apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql # Name of the resource and also its hostname
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306 # The port we
  selector:
    app: wordpress
    tier: mysql
